dist: xenial
language: scala

scala:
  - 2.13.0
  - 2.12.8
  - 2.11.12

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier


before_cache:
  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

stages:
  - validations
  - test

jobs:
  include:
    - stage: validations
      script: scripts/validate-code check
      name: "Code validations for source formatting"
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test
      name: "Run coverage tests"

after_success:
  - sbt coverageReport coveralls