dist: xenial
language: scala

scala:
  - 2.13.0
  - 2.13.1
  - 2.13.2
  - 2.13.3
  - 2.13.4
  - 2.12.12
  - 2.11.12

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

before_install:
  - pip install --user codecov

before_cache:
  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

stages:
  - validations
  - test

jobs:
  include:
    - stage: validations
      script: sbt ++$TRAVIS_SCALA_VERSION fmtCheck
      name: "Code validations for source formatting"
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test
      name: "Run coverage tests"

#removing coveralls for now
after_success:
  - sbt coverage coverageAggregate coverageReport
  - bash <(curl -s https://codecov.io/bash)
