name: Website
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
#  publish:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: olafurpg/setup-scala@v10
#      - uses: olafurpg/setup-gpg@v3
#      - run: sbt docs/docusaurusPublishGhpages
#        env:
#          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
  publish:
    name: Microsite
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.12]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Setup Jekyll
        run: gem install jekyll -v 4.0.0

      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.GIT_DEPLOY_KEY }}" | base64 --decode > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          cat <<EOT >> /home/runner/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile /home/runner/.ssh/id_rsa
          EOT

      - name: Build the microsite
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git config --global push.default simple
          sbt docs/ghpagesPushSite
        env:
          MICROSITE_TOKEN: ${{ secrets.MICROSITE_TOKEN }}
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
#addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
#https://github.com/scala-steward-org/scala-steward/blob/master/.github/workflows/ci.yml